name: Local Config
version: 0.0.1
schema: v1
models:
  - name: Qwen3.5
    provider: ollama
    model: qwen3.5:9b
    apiBase: http://192.168.8.183:11434
    promptTemplates:
      apply: |
        Original: {{{original_code}}}
        New: {{{new_code}}}
        Please generate the final code without any markers or explanations.
      edit: |
        `Here is the code before editing:
        \`\`\`{{{language}}}
        {{{codeToEdit}}}
        \`\`\`

        Here is the edit requested:
        "{{{userInput}}}"

        Here is the code after editing:
    roles:
      - chat
      - edit
      - apply   
      - rerank
  - name: Nomic-Embed-Text
    provider: ollama
    model: nomic-embed-text:latest
    apiBase: http://localhost:11434
    roles:
      - embed
  - name: Qwen2.5-coder
    provider: ollama
    model: qwen2.5-coder:1.5b
    apiBase: http://localhost:11434
    promptTemplates:
      autocomplete: |
        `
        globalThis.importantFunc = importantFunc
        <|fim_prefix|>{{{prefix}}}<|fim_suffix|>{{{suffix}}}<|fim_middle|>
        `
    roles:
      - autocomplete
mcpServers:
  - name: metamcp
    type: sse
    url: http://localhost:12008/metamcp/continue-dev/sse
